### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by mohanad1131** [AngeloJacobo/FPGA_RealTime_and_Static_Sobel_Edge_Detection#1]
dcm_24MHZ ,dcm_25MHZ and dcm_64 MHz are missing in source files

**Comment by AngeloJacobo** [comment]
Hi, source files for PLL instantiations are now added. ReadMe file is also updated.

**Comment by mohanad1131** [comment]
thanks but i think dcm_25MHZ is still not available

**Comment by AngeloJacobo** [comment]
Both `src1` and `src2` already have `dcm_25MHz.v`. May I know what specific source file is calling/instantiating the missing DCM_25MHZ? May I also know if you are using Xilinx ISE?

**Comment by mohanad1131** [comment]
` dcm_24MHz m1
   (// Clock in ports
    .clk(clk),      // IN
    // Clock out ports
    .cmos_xclk(cmos_xclk),     // OUT
    // Status and control signals
    .RESET(RESET),// IN
    .LOCKED(LOCKED));      // OUT
you are including dcm_24Mhz in mo-camera interface
`

**Comment by AngeloJacobo** [comment]
You're right, thanks! `dcm24_MHz.v` is now added. ReadMe file is also updated.

**Comment by mohanad1131** [comment]
Okay thanks Great work
